# 服务配置文件模板
spring:
  application:
    name: task
    desc: Task Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.task
  data:
    mongodb:
      uri:
  # consul config do not need to change
  redis:
    host:
    password:
    port:
    pool:
      maxActive: 16
      maxWait: -1
      maxIdle: 16
      minIdle: 0
  rabbitmq:
    virtual-host:
    username:
    password:
    addresses:
    listener:
      simple:
        concurrency: 10
        acknowledge-mode: auto
  cloud:
    consul:
      discovery:
        tags: dev
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 23910
server:
  port:  # 服务端口


time:
  analysis:
    maxhour: 7

devops:
  imageName:
  retry:
    attempt: 7
    interval: 1000

enc:
  key:
jasypt:
  encryptor:
    password:

codecc:
  node:
    host:

devopsGateway:
  idchost:

