# 服务配置文件模板
spring:
  application:
    name: task
    desc: Task Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.task
  data:
    mongodb:
      uri: mongodb://__MONGODB_USER__:__MONGODB_PASS__@__MONGODB_IP__:__MONGODB_PORT__/db_task

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 23910
server:
  port: __CODECC_TASK_PORT__ # 服务端口


time:
  analysis:
    maxhour: 7

devops:
  retry:
    attempt: 7
    interval: 1000

tof:
  rootpath: __TOF_ROOT_PATH_URL__
  codecc:
    appcode: __TOF_CODECC_APP_CODE__
    appsecret: __TOF_CODECC_APP_SECRET__

custom:
  projectName:
    svnName: __CUSTOM_PROJECT_NAME__
    svnPassword: ENC(__CUSTOM_SVN_PASS__)
    pcgName: __CUSTOM_PCG_NAME__
    pcgPassword: ENC(__CUSTOM_PCG_PASS__)
    tegName: __CUSTOM_PROJECT_NAME__
    tegPassword: ENC(__CUSTOM_TEG_PASS__)
    proxy: __CUSTOM_PROJECT_NAME_PROXY__

enc:
  key: __ENC_KEY__

jasypt:
  encryptor:
    password: __JASYPT_ENCRYPTOR__

dockerImage:
  account: __DOCKER_IMAGE__ACCOUNT__
  passwd: __DOCKER_IMAGE__PASSWD__