# Common config Template 重复的通用的配置抽离在到

spring:
  application:
    version: 4.0.0
  # consul config do not need to change
  redis:
    host: __REDIS_IP__
    password: __REDIS_PASS__
    port: __REDIS_PORT__
    pool:
      maxActive: 16
      maxWait: -1
      maxIdle: 16
      minIdle: 0
  rabbitmq:
    virtual-host:  __RABBITMQ_CODECC_VHOST__
    username: __RABBITMQ_USERNAME__
    password: __RABBITMQ_PASSWORD__
    addresses: __RABBITMQ_HOST__:__RABBITMQ__PORT__
  cloud:
    consul:
      discovery:
        tags: dev
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  #      port: 8080
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# http concurrency
server:
  servlet-path: /
  undertow:
    worker-threads: 100


# monitor path config
management:
  security:
    enabled: false
  context-path: /management


auth:
  envName: prod
  url: __CODECC_AUTH_URL__
  codeccCode: __APP_CODE__
  codeccSecret: __APP_TOKEN__
  systemId: __CODECC_SYSTEM_ID__
  codeccResourceType: __CODECC_RESOURCE_TYPE__
  pipelineResourceType: __PIPELINE_RESOURCE_TYPE__
  codeccServiceCode: __CODECC_SERVICE_CODE__
  pipelineServiceCode: __PIPELINE_SERVICE_CODE__

bkAuth:
  envName: prod
  url: __CODECC_BK_AUTH_URL__
  codeccCode: __APP_CODE__
  codeccSecret: __APP_TOKEN__
  systemId: __CODECC_SYSTEM_ID__
  codeccResourceType: __CODECC_RESOURCE_TYPE__
  pipelineResourceType: __PIPELINE_RESOURCE_TYPE__
  codeccServiceCode: __CODECC_SERVICE_CODE__
  pipelineServiceCode: __PIPELINE_SERVICE_CODE__

devopsGateway:
  host: __DEVOPS_GATEWAY_HOST__
  idchost: __DEVOPS_GATEWAY_IDC_HOST__

codeccGateway:
  host: __CODECC_GATEWAY_HOST__:__CODECC_GATEWAY_PORT__     #  codecc.blueking.com:80
  api: __CODECC_GATEWAY_API_URL__:__CODECC_GATEWAY_API_PORT__     #  codecc.blueking.com:80

codecc:
  encryptor:
    password: __CODECC_ENCRYPTOR_PASS__
  env: internal
  privatetoken: __CODECC_PRIVATETOKEN__
  classurl: __CODECC_CLASSURL__
  public:
    account: __CODECC_PUBLIC_ACCOUNT__
    password: __CODECC_PUBLIC_PASSWORD__
  node:
    host: __CODECC_NODE_HOST__
  gateway:
    host: __CODECC_GATEWAY_HOST__


certificate:
  platform: bkcodecc
  server: https://__LICENSE_HOST__:__LICENSE_PORT__/certificate

service-suffix: "-devops"

git:
  path: __GIT_PATH_URL__
  domain: __GIT_DOMAIN__
