# Common config Template 重复的通用的配置抽离在到

spring:
  application:
    version: 4.0.0
# consul config do not need to change
  cloud:
    consul:
      port: __BKCI_CONSUL_PORT__
      discovery:
        tags: __BKCI_CONSUL_TAG__
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
# redis config
  redis:
#   # Redis sentinel 集群方式配置
#    sentinel:
#      master: __REDIS_MASTER_NAME__
#      nodes: __REDIS_CLUSTER_HOST__:__REDIS_CLUSTER_PORT__
#   # Redis 单机配置方式
    host: __REDIS_IP__
    port: __REDIS_PORT__
    password: __REDIS_PASS__
    database: __REDIS_DB__
    pool:
      max-active: 16
      max-wait:  2000
# rabbitmq config
  rabbitmq:
    # 引擎核心业务MQ
    core:
      virtual-host: __RABBITMQ_VHOST__
      username: __RABBITMQ_USERNAME__
      password: __RABBITMQ_PASSWORD__
      addresses: __RABBITMQ_HOST__:__RABBITMQ_PORT__
    # 拓展功能模块MQ -- 可与core保持一致，也可分为两个不同实例
    extend:
      virtual-host: __RABBITMQ_VHOST__
      username: __RABBITMQ_USERNAME__
      password: __RABBITMQ_PASSWORD__
      addresses: __RABBITMQ_HOST__:__RABBITMQ_PORT__

service-suffix: "-__BKCI_CONSUL_TAG__"
# http concurrency
server:
  undertow:
    worker-threads: 100
    accesslog:
      enabled: true
      pattern: '%h %I "%{i,X-DEVOPS-UID}" [%{time,yyyyMMddHHmmss.S}] "%r" %s %D %b "%{i,Referer}" "%{i,User-Agent}"'
      dir: ${service.log.dir}

# gateway for system
devopsGateway:
  build: __HTTP_SCHEMA__://__BKCI_FQDN__        # for build agent like dev.devops.blueking.com:80
  host: __HTTP_SCHEMA__://__BKCI_FQDN__         # for web many be same to buildGateWay
  api: __HTTP_SCHEMA__://__BKCI_FQDN__          # for api many be same to host
  idc: __HTTP_SCHEMA__://__BKCI_FQDN__          # for idc many be same to host
  idcProxy: __HTTP_SCHEMA__://__BKCI_FQDN__     # for idc proxy many be same to host
  devnetProxy: __HTTP_SCHEMA__://__BKCI_FQDN__  # for devnet proxy many be same to host
  devnet: __HTTP_SCHEMA__://__BKCI_FQDN__       # for devnet many be same to host
  oss: __HTTP_SCHEMA__://__BKCI_FQDN__          # for oss many be same to host
  ossProxy: __HTTP_SCHEMA__://__BKCI_FQDN__     # for oss proxy many be same to host
  outer: __HTTP_SCHEMA__://__BKCI_FQDN__        # for internet domain
  outerApi: __HTTP_SCHEMA__://__BKCI_FQDN__     # for internet domain api
  
# certificate server 配置
certificate:
  server: https://__LICENSE_HOST__:__LICENSE_PORT__/certificate


#S3 Storage
s3:
  endpointUrl: __BKCI_S3_URL__
  accessKey: __BKCI_S3_ACCESSKEY__
  secretKey: __BKCI_S3_SECRETKEY__
  bucketName: __BKCI_S3_BUCKET__

auth:
  # idProvider为权限中心对接方式，sample(开源默认实现无鉴权)/ bk_login（蓝鲸登录) / client
  # 选择sample后以下配置无效
  idProvider: __AUTH_PROVIDER__
  grantType: rization_code
  principalType: user
  envName: prod
  #  开发时需要配置Host解析到iam.service.consul
  url: http://__BK_IAM_PRIVATE_ADDR__
  appCode: __APP_CODE__
  appSecret: __APP_TOKEN__
  bkloginUrl: __HTTP_SCHEMA__://__PAAS_FQDN__:__PAAS_HTTPS_PORT__/login/api/v2
  iamCallBackUser: __IAM_CALLBACK_USER__


#bk esb config for cd plugin in pipeline
esb:
  code: __APP_CODE__
  secret: __APP_TOKEN__
  job:
    url: __HTTP_SCHEMA__://__PAAS_FQDN__:__PAAS_HTTPS_PORT__/api/c/compapi/v2/job/
  gcloud:
    url: __HTTP_SCHEMA__://__PAAS_FQDN__:__PAAS_HTTPS_PORT__/api/c/compapi/v2/sops/
  cmdb:
    searchhosturl: __HTTP_SCHEMA__://__PAAS_FQDN__:__PAAS_HTTPS_PORT__/api/c/compapi/v2/
  iam:
    url: __HTTP_SCHEMA__://__PAAS_FQDN__:__PAAS_HTTPS_PORT__

# codecc config
codecc:
  host: __CODECC_HOST__:__CODECC_HTTP_PORT__

codeccGateway:
  gateway: __HTTP_SCHEMA__://__CODECC_HOST__:__CODECC_HTTP_PORT__
  gatewayWeb: __HTTP_SCHEMA__://__CODECC_FQDN__:__CODECC_HTTPS_PORT__
  api:
   createTask: /ms/task/api/service/task/
   updateTask: /ms/task/api/service/task/
   checkTaskExists: /ms/task/api/service/task/exists/
   deleteTask: /ms/task/api/service/task/
   codeCheckReport: /ms/api/
alert:
  users: ''
codeoa:
  api-key: __CODEOA_API_KEY__
  api-url: __CODEOA_API_URL__
  git-url: __CODEOA_GIT_URL__

bk:
  paas:
    host: __HTTP_SCHEMA__://__PAAS_FQDN__:__PAAS_HTTPS_PORT__

bkci:
  security:
    public-key: "__BKCI_RSA_PUBLIC_KEY__"
    private-key: "__BKCI_RSA_PRIVATE_KEY__"
    enable: false
