# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_log?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __BK_CI_MYSQL_USER__
    password: __BK_CI_MYSQL_PASSWORD__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21914
server:
  port: __BK_CI_LOG_API_PORT__

elasticsearch:
  ip: __BKCI_ES_IP__
  port: __BKCI_ES_PORT__
  cluster: __BKCI_ES_CLUSTER__
  name: DEVOPS
#  ES集群如果不要求账号密码认证，则可以去掉以下2个ES的访问账号密码配置项或留空
  username: __BK_CI_ES_USER__
  password: __BK_CI_ES_PASSWORD__
#  ES集群如果要求HTTPS协议请求，则需要需要打开以下5个配置项， 设置keystore文件和truststore文件以及密码
#  https: true
#  keystore:
#    filePath:
#    password:
#  truststore:
#    filePath:
#    password: