# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__BK_CI_MYSQL_ADDR__/devops_ci_ticket?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __BK_CI_MYSQL_USER__
    password: __BK_CI_MYSQL_PASSWORD__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21915
server:
  port: __BK_CI_TICKET_API_PORT__


cert:
  aes-key: "gHi(xG9Af)jEvCx&"

credential:
  mixer: "******"
  aes-key: "G/I%yP{?ST}2TXPg"
